GLA-712 Shopify link to customer portal
CondeNast/recharge-api-node pull request #1
Opened 2022-09-09 19:20 UTC by SalvadorEspinosa

Addresses https://cnissues.atlassian.net/browse/GLA-712

## Summary

Add endpoint to get customer portal url.

---

## Testing

---

## Design

---

## Review Checklist

Please complete these steps before requesting code review:

- [x] Branch is rebased & updated with the latest code from `master`
- [x] This PR is clearly titled and provides a description, testing steps, and adequate context for reviewers
- [ ] This PR is passing the Github Action build
- [ ] Add/Update feature related document, sequence diagram and api specification (if applicable)

## Releasing

Once your code is approved by a minimum of 2 reviewers:

- [ ] Squash and merge. (Copy and paste the PR title or a one liner summary as the commit message)

2022-09-09 19:51 UTC, sretanapro approved these changes

2022-09-09 21:39 UTC, sk8Guerra approved these changes

2022-09-12 14:28 UTC, psavage approved these changes

2022-09-12 14:34 UTC, psavage requested changes
Please add the new getPortalUrl method to README.md

2022-09-12 15:28 UTC, psavage approved these changes

2022-09-12 16:11 UTC, sretanapro approved these changes

2022-09-12 16:16 UTC, sk8Guerra approved these changes

2022-09-12 16:48 UTC, merged